### ISSUE TITLE
Add pytest/tox/codecov/travis/appveyor/circle

### ISSUE THREAD

**Issue by altendky** [sunu/qt5reactor#21]
I recently did ebroecker/canmatrix#185 so I'll presumably end up with pretty much the same thing.

**Comment by altendky** [comment]
@crwood or @sunu, could we get these setup?

- [ ] [Travis](https://travis-ci.org/) build
- [ ] [Appveyor](https://www.appveyor.com/) build
  - [ ] Set the `Build version format` to `{build}`
  - [ ] Check AppVeyor to only build branches with `appveyor.yml`
  - [ ] Get the badge URL from under `Settings` > `Badges`
    - They're the only one that has a 'private' value in the badge URL... `:|`
- [ ] [Codecov](https://codecov.io/)
- [ ] [Circle](https://circleci.com/) build (mostly for OS X)
  - [ ] If you email them they will enable OS X builds

Hopefully I'm remembering all the pieces.

**Comment by crwood** [comment]
Hi @altendky,

Thank you so much for taking the initiative on this! (And my apologies for the very late response here -- I was originally away when I got your mention and completely forgot to follow up...)

I just tried switching on Travis-CI but, regrettably, I don't seem to have the requisite permissions (and I assume the other services will follow similarly):

![screenshot](https://user-images.githubusercontent.com/882430/46098924-70b40780-c193-11e8-8625-60a062d1203d.png)

@sunu Any chance you could switch these on for us?

**Comment by altendky** [comment]
@crwood and @sunu, thanks.  So Travis and AppVeyor seem to be running.

**Comment by altendky** [comment]
*bump* for codecov, circle, and a review.  Cheers.

**Comment by sunu** [comment]
Hi @altendky,
Travis seems to support OS X builds. Can we use that? And I think I have enabled codecov already. Let me know if that's not the case though.

**Comment by altendky** [comment]
@sunu, I had heard bad things about Travis OS X.  Really high latency for builds.  I started working with CircleCI when working on Twisted.  Honestly, I'm not sure why I want to use Travis at all anymore other than it being the defacto standard.  It really bugs me that you can't store build artifacts there at all.  Both CircleCI and AppVeyor store artifacts for you and both do Linux.  Now if only we could get Linux/OS X/Windows in one place...

Anyways, I'll give Travis OS X a shot.

Hmm, yes, codecov is hooked up.  For some reason I didn't check it off in my list...

**Comment by altendky** [comment]
Well, by golly gee whiz...

https://blog.travis-ci.com/2018-10-11-windows-early-release

Now if only they really supported Python on either Windows or OS X.  From what I've seen so far we're expected to use homebrew to get pyenv to get the Python we want.  That's just silly.

I may yet beat Travis into submission just for the sake of being able to go one place for everything, but it seems I'll have to build a framework of sorts for it including external storage to avoid rebuilding Python etc for every single job.  On the other hand I've setup a couple of Linux and OS X configs for CircleCI without getting too horribly upset.

**Comment by altendky** [comment]
@crwood, @sunu, so at this point I would expect OS X testing to be done on CircleCI.  If we aren't going to set that up are we up for reviewing and accepting this with just Linux and Windows as CI test targets?

**Comment by crwood** [comment]
I agree both that macOS testing is important and that Travis-CI is less-than-optimal for it (it's been a huge pain, in my experience, for the sorts of reasons that @altendky alludes to -- among several others...). And while I'm unfamiliar with configuring Circle-CI myself, I have heard good things about it from colleagues and wouldn't want to see @altendky's generous efforts here become squandered.

@sunu Could you please enable Circle-CI for this repo and/or grant @altendky the appropriate permissions required to manage it?

**Comment by sunu** [comment]
I have nothing against Circle-CI. Just that having to email them to enable OS X support was a little inconvenient and I was being lazy. Just emailed them about it now. Hopefully we'll have it enabled soon.
The project is already enabled in CircleCI. So if you want to dump Travis for good and move everything to CircleCI, please go ahead.

**Comment by altendky** [comment]
@sunu, awesome, I'll try to get that going now.  I haven't made up my mind personally on Travis.  With them doing all three platforms now in one place it's tempting, but the artifact and Python situation will have to get better...  Let's go with all three for now and we'll see what happens.

**Comment by altendky** [comment]
Resolved by #24.
