### ISSUE TITLE
Please update the pypi version

### ISSUE THREAD

**Issue by om26er** [sunu/qt5reactor#35]
I am creating a snap that uses this reactor, it would be very convenient if the latest version was available from pypi.

Please push the latest to pypi :-)

**Comment by altendky** [comment]
We should get #34 done first even if we leave the pyside2 tests failing for now.

**Comment by om26er** [comment]
ping @altendky, since the CI is fixed, can you please do a push to pypi ?

**Comment by altendky** [comment]
@om26er, I'm sorry but I don't think I have any rights to PyPI for qt5reactor.  From what I see the pyside2 support is the only non-CI addition.  Is that what you are looking for?

**Comment by om26er** [comment]
>  Is that what you are looking for?

Yes, I need PySide2 support, currently we have pinned github master pinned in our `requirements.txt`

**Comment by altendky** [comment]
@crwood, @sunu, I get the timing right now (for at least some) but...  \*bump\*.

**Comment by sunu** [comment]
@altendky Hi! If you share your PyPI ID with me, I can share access to push out releases. Let me know if that would be okay

**Comment by altendky** [comment]
@sunu, just `altendky` :]

**Comment by sneakypete81** [comment]
@sunu, @altendky: is this still blocked? It would be great to have a PyPI release to use.

**Comment by altendky** [comment]
@sneakypete81, I have the power now...  Just need to find the time.  :|

**Comment by altendky** [comment]
https://pypi.org/project/qt5reactor/0.6/

Please confirm it is working for you and then we can close this issue.

**Comment by sneakypete81** [comment]
Perfect, thanks!
